name: Deploy Projeto Firebase React

on:
  push:
    branches: ["feat/projeto-next"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projeto/projetoReact # Define a pasta raiz para todos os comandos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: './projeto/projetoReact/package-lock.json'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        shell: bash
        run: npm test -- --watchAll=false || true  # O "|| true" força o sucesso mesmo com erro
        env:
          CI: true
      - name: Build Project
        run: npm run build # Agora usa o react-scripts build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./projeto/projetoReact/build
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Discord Notification
        if: always()
        uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"