name: CI/CD Projeto React

on:
  push:
    branches: ["feat/projeto-next"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          # Caminho para o lock file na subpasta
          cache-dependency-path: 'projeto/projetoReact/package-lock.json'

      - name: Install Dependencies
        run: |
          cd projeto/projetoReact
          npm install

      - name: Run Tests
        run: |
          cd projeto/projetoReact
          npm test

      - name: Build Project
        run: |
          cd projeto/projetoReact
          npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O Next.js gera a pasta 'out' dentro da pasta do projeto
          path: ./projeto/projetoReact/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Integração com Discord (Avisa após o deploy final)
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true